#Role que se creara para dar permisos de creacion de pods y deployment
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: runner-gitlab-runner-deployments
subjects:
- kind: ServiceAccount
  namespace: "gitlab-managed-apps"
  name: "default"
  apiGroup: ""
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: "deployment-manager"
